def throw_exception():
    print('Will raise an Exception')
    raise Exception('Raised inside `throw_exception`')
    print('This message won\'t be printed')
